version: 2
project_name: hue-tf
dist: dist/cli
builds:
  - id: cli
    main: ./cmd/hue-tf
    env: [CGO_ENABLED=0]
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags: [-trimpath]
    ldflags: ['-s -w']
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    binary: hue-tf
archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  draft: true
changelog:
  disable: true
